"""
setup_project.py
================
Run this once from any folder:
    python setup_project.py

It will create the entire world_cup_predictor/ project next to this file.
"""

import os

BASE = "world_cup_predictor"

# ── helpers ──────────────────────────────────────────────────────────────────

def mkdir(path):
    os.makedirs(path, exist_ok=True)

def write(path, content):
    mkdir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.lstrip("\n"))
    print(f"  created  {path}")

# ══════════════════════════════════════════════════════════════════════════════
#  FILE CONTENTS
# ══════════════════════════════════════════════════════════════════════════════

FILES = {}

# ── requirements.txt ─────────────────────────────────────────────────────────
FILES["requirements.txt"] = """
pandas>=2.0
numpy>=1.24
scikit-learn>=1.3
xgboost>=2.0
lightgbm>=4.0
shap>=0.44
streamlit>=1.32
plotly>=5.20
matplotlib>=3.8
seaborn>=0.13
joblib>=1.3
tqdm>=4.66
"""

# ── .gitignore ────────────────────────────────────────────────────────────────
FILES[".gitignore"] = """
data/raw/
data/processed/
models/*.pkl
__pycache__/
.ipynb_checkpoints/
*.env
*.pyc
.DS_Store
"""

# ── README.md ─────────────────────────────────────────────────────────────────
FILES["README.md"] = """
# ⚽ World Cup 2026 Predictor

A data-driven football match predictor using ELO ratings, squad strength,
player form scores, and a Gradient Boosting classifier.

## Quickstart

```bash
pip install -r requirements.txt

# 1. Drop Kaggle CSVs into data/raw/
#    results.csv, goalscorers.csv, shootouts.csv,
#    fifa_players.csv, rankings.csv, player_ratings.csv

# 2. Run the full pipeline
python pipeline.py

# 3. Launch the web app
streamlit run app/app.py
```

## Project Layout

```
world_cup_predictor/
├── data/raw/          ← Kaggle files (never edit)
├── data/processed/    ← Generated by pipeline
├── data/external/     ← Small JSON reference files
├── notebooks/         ← Exploration notebooks
├── src/               ← All production Python code
├── models/            ← Saved .pkl model files
├── app/               ← Streamlit web app
├── tests/             ← Unit tests
└── pipeline.py        ← Run everything in one command
```

## Expected Accuracy
| Model | Accuracy |
|-------|----------|
| Baseline (always home win) | ~45% |
| ELO only | ~58% |
| ELO + form | ~62% |
| Full feature set + GBM | ~65–68% |
| + Squad / player data | ~70%+ |
"""

# ── pipeline.py ───────────────────────────────────────────────────────────────
FILES["pipeline.py"] = """
\"\"\"
pipeline.py  —  Master script. Run once to rebuild everything.
    python pipeline.py
\"\"\"

import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from src.data.cleaner import clean_data
from src.elo.elo_runner import run_elo
from src.features.feature_builder import build_features
from src.models.train import train_model


def main():
    print("\\n=== Step 1 / 4 : Cleaning raw data ===")
    clean_data()

    print("\\n=== Step 2 / 4 : Computing ELO ratings ===")
    run_elo()

    print("\\n=== Step 3 / 4 : Building feature table ===")
    build_features()

    print("\\n=== Step 4 / 4 : Training models ===")
    train_model()

    print("\\n✅  Pipeline complete!")
    print("   Launch the app with:  streamlit run app/app.py")


if __name__ == "__main__":
    main()
"""

# ── src/__init__.py ───────────────────────────────────────────────────────────
FILES["src/__init__.py"] = ""
FILES["src/data/__init__.py"] = ""
FILES["src/elo/__init__.py"] = ""
FILES["src/features/__init__.py"] = ""
FILES["src/models/__init__.py"] = ""
FILES["src/utils/__init__.py"] = ""

# ── src/utils/constants.py ────────────────────────────────────────────────────
FILES["src/utils/constants.py"] = """
\"\"\"
All magic numbers live here. Change once — affects the whole project.
\"\"\"

# ELO K-factors per tournament importance
K_FACTORS = {
    "FIFA World Cup": 40,
    "FIFA World Cup qualification": 30,
    "UEFA Euro": 35,
    "UEFA Euro qualification": 28,
    "Copa América": 35,
    "AFC Asian Cup": 30,
    "Africa Cup of Nations": 30,
    "Friendly": 15,
    "default": 20,
}

# Home ground advantage (added to home team ELO before expected score calc)
HOME_ELO_BONUS = 100

# Starting ELO for every team
DEFAULT_ELO = 1500

# How many recent matches to use for form
FORM_WINDOW = 5

# Weighted decay for recent matches (most recent first)
FORM_DECAY_WEIGHTS = [0.35, 0.25, 0.20, 0.12, 0.08]

# Position importance weights (must sum to 1.0)
POSITION_WEIGHTS = {
    "GK":  0.15,
    "CB":  0.12,
    "LB":  0.08,
    "RB":  0.08,
    "CDM": 0.10,
    "CM":  0.09,
    "CAM": 0.10,
    "LW":  0.07,
    "RW":  0.07,
    "ST":  0.14,
}

# Squad selection weights
STARTER_WEIGHT = 0.85
BENCH_WEIGHT   = 0.15

# Average squad strength and form (used to normalise deltas)
AVG_SQUAD_STRENGTH = 70.0
AVG_FORM_SCORE     = 6.5

# ELO boost per squad-strength point above average
SQUAD_ELO_SCALE = 3.0

# ELO boost per form point above average
FORM_ELO_SCALE = 10.0

# Known star players per national team
STAR_PLAYERS = {
    "Brazil":      ["Vinicius Jr", "Rodrygo"],
    "France":      ["Kylian Mbappe", "Antoine Griezmann"],
    "Argentina":   ["Lionel Messi", "Julian Alvarez"],
    "England":     ["Jude Bellingham", "Harry Kane"],
    "Spain":       ["Pedri", "Lamine Yamal"],
    "Germany":     ["Florian Wirtz", "Jamal Musiala"],
    "Portugal":    ["Cristiano Ronaldo", "Bruno Fernandes"],
    "Netherlands": ["Virgil van Dijk", "Cody Gakpo"],
    "Belgium":     ["Kevin De Bruyne", "Romelu Lukaku"],
    "Italy":       ["Federico Chiesa", "Nicolo Barella"],
}
"""

# ── src/utils/helpers.py ──────────────────────────────────────────────────────
FILES["src/utils/helpers.py"] = """
\"\"\"
Small reusable utility functions.
\"\"\"

import math
import pandas as pd


def safe_divide(a: float, b: float, default: float = 0.0) -> float:
    \"\"\"Return a/b, or default if b is zero.\"\"\"
    return a / b if b != 0 else default


def date_diff_days(d1, d2) -> int:
    \"\"\"Return absolute difference in days between two date-like values.\"\"\"
    return abs((pd.Timestamp(d1) - pd.Timestamp(d2)).days)


def clamp(value: float, lo: float, hi: float) -> float:
    \"\"\"Clamp value between lo and hi.\"\"\"
    return max(lo, min(hi, value))


def weighted_mean(values, weights) -> float:
    \"\"\"Weighted average. Lists must be the same length.\"\"\"
    if not values:
        return 0.0
    total_w = sum(weights[:len(values)])
    return sum(v * w for v, w in zip(values, weights)) / total_w if total_w else 0.0


def get_k_factor(tournament: str, k_map: dict) -> float:
    \"\"\"Look up K-factor for a tournament string.\"\"\"
    for key, val in k_map.items():
        if key.lower() in tournament.lower():
            return val
    return k_map.get("default", 20)
"""

# ── src/data/loader.py ────────────────────────────────────────────────────────
FILES["src/data/loader.py"] = """
\"\"\"
Functions to load raw CSVs from data/raw/.
\"\"\"

import os
import pandas as pd

RAW_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "raw")


def _path(filename: str) -> str:
    return os.path.join(RAW_DIR, filename)


def load_results() -> pd.DataFrame:
    return pd.read_csv(_path("results.csv"))


def load_goalscorers() -> pd.DataFrame:
    return pd.read_csv(_path("goalscorers.csv"))


def load_shootouts() -> pd.DataFrame:
    return pd.read_csv(_path("shootouts.csv"))


def load_fifa_players() -> pd.DataFrame:
    return pd.read_csv(_path("fifa_players.csv"))


def load_rankings() -> pd.DataFrame:
    return pd.read_csv(_path("rankings.csv"))


def load_player_ratings() -> pd.DataFrame:
    return pd.read_csv(_path("player_ratings.csv"))
"""

# ── src/data/cleaner.py ───────────────────────────────────────────────────────
FILES["src/data/cleaner.py"] = """
\"\"\"
Clean raw results.csv and write data/processed/matches_clean.csv.
\"\"\"

import os
import pandas as pd
from src.data.loader import load_results

PROCESSED_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")

# Normalise inconsistent country / team name spellings found in the Kaggle dataset
TEAM_NAME_MAP = {
    "USA":                      "United States",
    "IR Iran":                  "Iran",
    "Korea Republic":           "South Korea",
    "Korea DPR":                "North Korea",
    "Czech Republic":           "Czechia",
    "Cape Verde Islands":       "Cape Verde",
    "St. Kitts and Nevis":      "Saint Kitts and Nevis",
    "São Tomé and Príncipe":    "Sao Tome and Principe",
}


def _normalise_team_names(df: pd.DataFrame) -> pd.DataFrame:
    df["home_team"] = df["home_team"].replace(TEAM_NAME_MAP)
    df["away_team"] = df["away_team"].replace(TEAM_NAME_MAP)
    return df


def clean_data() -> pd.DataFrame:
    os.makedirs(PROCESSED_DIR, exist_ok=True)
    df = load_results()

    # Parse dates
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date", "home_team", "away_team", "home_score", "away_score"])

    # Fix team names
    df = _normalise_team_names(df)

    # Add result column: 0=home win, 1=draw, 2=away win
    df["result"] = (
        df.apply(
            lambda r: 0 if r.home_score > r.away_score
            else (1 if r.home_score == r.away_score else 2),
            axis=1,
        )
    )

    # Add a simple tournament weight
    def _tw(t):
        t = str(t).lower()
        if "world cup" in t and "qualif" not in t:
            return 3
        if "qualif" in t:
            return 2
        if "friendly" in t:
            return 1
        return 2

    df["tournament_weight"] = df["tournament"].apply(_tw)
    df = df.sort_values("date").reset_index(drop=True)

    out = os.path.join(PROCESSED_DIR, "matches_clean.csv")
    df.to_csv(out, index=False)
    print(f"  Saved {len(df):,} clean matches → {out}")
    return df
"""

# ── src/elo/base_elo.py ───────────────────────────────────────────────────────
FILES["src/elo/base_elo.py"] = """
\"\"\"
Core ELO formula and K-factor logic.
\"\"\"

from src.utils.constants import HOME_ELO_BONUS, DEFAULT_ELO
from src.utils.helpers import get_k_factor
from src.utils.constants import K_FACTORS


def expected_score(elo_a: float, elo_b: float) -> float:
    \"\"\"Probability that team A beats team B.\"\"\"
    return 1.0 / (1.0 + 10.0 ** ((elo_b - elo_a) / 400.0))


def new_elo(old_elo: float, k: float, actual: float, expected: float) -> float:
    \"\"\"Single ELO update step.\"\"\"
    return old_elo + k * (actual - expected)


def update_match_elo(
    elo: dict,
    home: str,
    away: str,
    home_score: int,
    away_score: int,
    is_neutral: bool,
    tournament: str,
) -> None:
    \"\"\"
    Update elo[home] and elo[away] in-place after one match.
    elo is a defaultdict(lambda: DEFAULT_ELO).
    \"\"\"
    k = get_k_factor(tournament, K_FACTORS)
    bonus = 0 if is_neutral else HOME_ELO_BONUS

    exp_home = expected_score(elo[home] + bonus, elo[away])

    if home_score > away_score:
        actual = 1.0
    elif home_score == away_score:
        actual = 0.5
    else:
        actual = 0.0

    elo[home] = new_elo(elo[home], k, actual, exp_home)
    elo[away] = new_elo(elo[away], k, 1.0 - actual, 1.0 - exp_home)
"""

# ── src/elo/player_elo.py ─────────────────────────────────────────────────────
FILES["src/elo/player_elo.py"] = """
\"\"\"
Squad Strength Score (SSS) and form adjustments on top of base ELO.
\"\"\"

import pandas as pd
from src.utils.constants import (
    POSITION_WEIGHTS, FORM_DECAY_WEIGHTS, FORM_WINDOW,
    STARTER_WEIGHT, BENCH_WEIGHT,
    AVG_SQUAD_STRENGTH, AVG_FORM_SCORE,
    SQUAD_ELO_SCALE, FORM_ELO_SCALE,
    STAR_PLAYERS,
)
from src.utils.helpers import weighted_mean, clamp


def player_strength_score(row: pd.Series) -> float:
    \"\"\"
    Compute a single Player Strength Score (PSS 0-100) from FIFA attributes.
    Expects columns: overall, potential, composure, stamina, reactions.
    A 'form' column is used if present.
    \"\"\"
    weights = {
        "overall":    0.40,
        "potential":  0.10,
        "composure":  0.10,
        "stamina":    0.08,
        "reactions":  0.07,
    }
    score = sum(row.get(col, 70) * w for col, w in weights.items())
    if "form" in row.index:
        score += row["form"] * 0.25
    else:
        score += 70 * 0.25  # neutral default
    return round(clamp(score, 0, 100), 2)


def squad_strength_score(
    team_name: str,
    fifa_df: pd.DataFrame,
    injured_players: list = None,
) -> float:
    \"\"\"
    Weighted average PSS for the best available 11 + bench.
    \"\"\"
    injured_players = injured_players or []
    squad = (
        fifa_df[
            (fifa_df["nationality"] == team_name)
            & (~fifa_df["short_name"].isin(injured_players))
        ]
        .sort_values("PSS", ascending=False)
    )

    if squad.empty:
        return AVG_SQUAD_STRENGTH

    starters = squad.head(11)["PSS"].values
    bench    = squad.iloc[11:18]["PSS"].values

    sss = starters.mean() * STARTER_WEIGHT
    if len(bench):
        sss += bench.mean() * BENCH_WEIGHT
    return round(sss, 2)


def recent_form_score(
    player_name: str,
    as_of_date,
    ratings_df: pd.DataFrame,
) -> float:
    \"\"\"
    Weighted average of last FORM_WINDOW match ratings for one player.
    ratings_df must have: player_name, date, rating (0-10), goals, assists.
    \"\"\"
    recent = (
        ratings_df[
            (ratings_df["player_name"] == player_name)
            & (ratings_df["date"] < pd.Timestamp(as_of_date))
        ]
        .sort_values("date", ascending=False)
        .head(FORM_WINDOW)
    )

    if recent.empty:
        return AVG_FORM_SCORE

    w = FORM_DECAY_WEIGHTS[: len(recent)]
    base = weighted_mean(recent["rating"].tolist(), w)
    goal_bonus   = recent["goals"].sum()   * 0.10
    assist_bonus = recent["assists"].sum() * 0.05
    return round(clamp(base + goal_bonus + assist_bonus, 0, 10), 2)


def team_form_score(
    lineup: list,          # [(player_name, position), ...]
    as_of_date,
    ratings_df: pd.DataFrame,
) -> float:
    \"\"\"
    Position-weighted team form score.
    \"\"\"
    if not lineup:
        return AVG_FORM_SCORE

    total, weight_sum = 0.0, 0.0
    for player, position in lineup:
        form = recent_form_score(player, as_of_date, ratings_df)
        w    = POSITION_WEIGHTS.get(position, 0.08)
        total      += form * w
        weight_sum += w
    return round(total / weight_sum if weight_sum else AVG_FORM_SCORE, 2)


def adjusted_elo(
    base_elo: float,
    squad_strength: float,
    team_form: float,
) -> float:
    \"\"\"
    Adjust base ELO using squad quality and recent player form.
    \"\"\"
    squad_delta = (squad_strength - AVG_SQUAD_STRENGTH) * SQUAD_ELO_SCALE
    form_delta  = (team_form      - AVG_FORM_SCORE)     * FORM_ELO_SCALE
    return round(base_elo + squad_delta + form_delta, 1)


def star_player_score(
    team: str,
    injured_list: list,
    fifa_df: pd.DataFrame,
) -> float:
    \"\"\"
    Average PSS of available star players. Returns 0 if team not in STAR_PLAYERS.
    \"\"\"
    stars = STAR_PLAYERS.get(team, [])
    if not stars:
        return AVG_SQUAD_STRENGTH

    available = [p for p in stars if p not in injured_list]
    scores = []
    for p in available:
        row = fifa_df[fifa_df["short_name"] == p]
        if not row.empty:
            scores.append(float(row.iloc[0]["PSS"]))
        else:
            scores.append(75.0)
    return round(sum(scores) / len(stars), 2)  # penalise missing stars
"""

# ── src/elo/elo_runner.py ─────────────────────────────────────────────────────
FILES["src/elo/elo_runner.py"] = """
\"\"\"
Loop through every match in matches_clean.csv and build elo_history.csv.
\"\"\"

import os
from collections import defaultdict

import pandas as pd
from tqdm import tqdm

from src.utils.constants import DEFAULT_ELO
from src.elo.base_elo import update_match_elo

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")


def run_elo() -> pd.DataFrame:
    matches_path = os.path.join(PROCESSED, "matches_clean.csv")
    if not os.path.exists(matches_path):
        raise FileNotFoundError("Run clean_data() first.")

    df = pd.read_csv(matches_path, parse_dates=["date"])
    elo: dict = defaultdict(lambda: DEFAULT_ELO)

    records = []

    for _, row in tqdm(df.iterrows(), total=len(df), desc="ELO"):
        home, away = row.home_team, row.away_team

        # Record ELO before the match
        records.append({
            "date":       row.date,
            "home_team":  home,
            "away_team":  away,
            "home_elo_before": round(elo[home], 1),
            "away_elo_before": round(elo[away], 1),
        })

        update_match_elo(
            elo, home, away,
            int(row.home_score), int(row.away_score),
            bool(row.neutral), str(row.tournament),
        )

        # Store post-match ELO too
        records[-1]["home_elo_after"] = round(elo[home], 1)
        records[-1]["away_elo_after"] = round(elo[away], 1)

    history = pd.DataFrame(records)
    out = os.path.join(PROCESSED, "elo_history.csv")
    history.to_csv(out, index=False)
    print(f"  Saved ELO history ({len(history):,} rows) → {out}")

    # Also save current ELO snapshot for every team
    snapshot = pd.DataFrame(
        [{"team": t, "elo": round(v, 1)} for t, v in elo.items()]
    ).sort_values("elo", ascending=False).reset_index(drop=True)
    snap_out = os.path.join(PROCESSED, "elo_snapshot.csv")
    snapshot.to_csv(snap_out, index=False)
    print(f"  Saved ELO snapshot ({len(snapshot)} teams) → {snap_out}")

    return history
"""

# ── src/features/match_features.py ───────────────────────────────────────────
FILES["src/features/match_features.py"] = """
\"\"\"
Compute per-match features: H2H stats, venue form, days rest, etc.
\"\"\"

import pandas as pd
import numpy as np
from src.utils.helpers import safe_divide, date_diff_days


def h2h_stats(df: pd.DataFrame, home: str, away: str, before_date) -> dict:
    \"\"\"
    Last-5 head-to-head record between home and away before a given date.
    \"\"\"
    mask = (
        (
            ((df.home_team == home) & (df.away_team == away))
            | ((df.home_team == away) & (df.away_team == home))
        )
        & (df.date < pd.Timestamp(before_date))
    )
    h2h = df[mask].sort_values("date", ascending=False).head(5)

    home_wins, draws, away_wins = 0, 0, 0
    for _, r in h2h.iterrows():
        if r.home_team == home:
            if r.home_score > r.away_score:
                home_wins += 1
            elif r.home_score == r.away_score:
                draws += 1
            else:
                away_wins += 1
        else:
            if r.away_score > r.home_score:
                home_wins += 1
            elif r.home_score == r.away_score:
                draws += 1
            else:
                away_wins += 1

    return {"h2h_home_wins": home_wins, "h2h_draws": draws, "h2h_away_wins": away_wins}


def venue_form(df: pd.DataFrame, team: str, city: str, before_date) -> float:
    \"\"\"
    Team's win rate at a specific city in past matches.
    \"\"\"
    mask = (
        ((df.home_team == team) | (df.away_team == team))
        & (df.city == city)
        & (df.date < pd.Timestamp(before_date))
    )
    past = df[mask].tail(10)
    if past.empty:
        return 0.5

    wins = 0
    for _, r in past.iterrows():
        if r.home_team == team and r.home_score > r.away_score:
            wins += 1
        elif r.away_team == team and r.away_score > r.home_score:
            wins += 1
    return round(safe_divide(wins, len(past)), 3)


def recent_form_points(
    df: pd.DataFrame, team: str, before_date, last_n: int = 5
) -> float:
    \"\"\"
    Points from last N matches (W=3, D=1, L=0).  Returns average points per match.
    \"\"\"
    mask = (
        ((df.home_team == team) | (df.away_team == team))
        & (df.date < pd.Timestamp(before_date))
    )
    recent = df[mask].sort_values("date", ascending=False).head(last_n)
    if recent.empty:
        return 1.0  # neutral default

    pts = 0
    for _, r in recent.iterrows():
        if r.home_team == team:
            pts += 3 if r.home_score > r.away_score else (1 if r.home_score == r.away_score else 0)
        else:
            pts += 3 if r.away_score > r.home_score else (1 if r.home_score == r.away_score else 0)
    return round(safe_divide(pts, len(recent)), 3)


def days_since_last_match(df: pd.DataFrame, team: str, before_date) -> int:
    \"\"\"
    Number of days since team's previous match before the given date.
    \"\"\"
    mask = (
        ((df.home_team == team) | (df.away_team == team))
        & (df.date < pd.Timestamp(before_date))
    )
    past = df[mask].sort_values("date", ascending=False)
    if past.empty:
        return 30  # default
    return date_diff_days(before_date, past.iloc[0].date)


def goals_avg(df: pd.DataFrame, team: str, before_date, last_n: int = 10) -> tuple:
    \"\"\"
    Returns (avg_goals_scored, avg_goals_conceded) over last N matches.
    \"\"\"
    mask = (
        ((df.home_team == team) | (df.away_team == team))
        & (df.date < pd.Timestamp(before_date))
    )
    recent = df[mask].sort_values("date", ascending=False).head(last_n)
    if recent.empty:
        return 1.2, 1.2

    scored, conceded = [], []
    for _, r in recent.iterrows():
        if r.home_team == team:
            scored.append(r.home_score)
            conceded.append(r.away_score)
        else:
            scored.append(r.away_score)
            conceded.append(r.home_score)

    return round(np.mean(scored), 3), round(np.mean(conceded), 3)
"""

# ── src/features/player_features.py ──────────────────────────────────────────
FILES["src/features/player_features.py"] = """
\"\"\"
Compute PSS, SSS, and star-player availability features.
\"\"\"

import os
import pandas as pd
from src.data.loader import load_fifa_players
from src.elo.player_elo import (
    player_strength_score,
    squad_strength_score,
    star_player_score,
)

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")


def build_pss_table() -> pd.DataFrame:
    \"\"\"
    Compute PSS for every player in the FIFA dataset and save to
    data/processed/player_pss.csv.
    \"\"\"
    os.makedirs(PROCESSED, exist_ok=True)
    fifa = load_fifa_players()

    # Ensure expected columns exist (fill with 70 if missing)
    for col in ["overall", "potential", "composure", "stamina", "reactions"]:
        if col not in fifa.columns:
            fifa[col] = 70

    fifa["PSS"] = fifa.apply(player_strength_score, axis=1)
    out = os.path.join(PROCESSED, "player_pss.csv")
    fifa[["short_name", "nationality", "club_name", "PSS"]].to_csv(out, index=False)
    print(f"  Saved PSS for {len(fifa):,} players → {out}")
    return fifa


def build_squad_strength_table(fifa_df: pd.DataFrame) -> pd.DataFrame:
    \"\"\"
    Compute SSS for every national team and save to
    data/processed/squad_strength.csv.
    \"\"\"
    os.makedirs(PROCESSED, exist_ok=True)
    teams = fifa_df["nationality"].dropna().unique()
    rows = []
    for team in teams:
        sss = squad_strength_score(team, fifa_df)
        rows.append({"team": team, "squad_strength": sss})
    df = pd.DataFrame(rows).sort_values("squad_strength", ascending=False)
    out = os.path.join(PROCESSED, "squad_strength.csv")
    df.to_csv(out, index=False)
    print(f"  Saved squad strength for {len(df)} teams → {out}")
    return df
"""

# ── src/features/feature_builder.py ──────────────────────────────────────────
FILES["src/features/feature_builder.py"] = """
\"\"\"
Merge ELO history + match features + player features into features_final.csv.
\"\"\"

import os
import pandas as pd
from tqdm import tqdm

from src.features.match_features import (
    h2h_stats, venue_form, recent_form_points,
    days_since_last_match, goals_avg,
)

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")


def build_features() -> pd.DataFrame:
    matches_path   = os.path.join(PROCESSED, "matches_clean.csv")
    elo_path       = os.path.join(PROCESSED, "elo_history.csv")
    squad_path     = os.path.join(PROCESSED, "squad_strength.csv")

    for p in [matches_path, elo_path]:
        if not os.path.exists(p):
            raise FileNotFoundError(f"Missing {p} — run earlier pipeline steps first.")

    matches = pd.read_csv(matches_path, parse_dates=["date"])
    elo_hist = pd.read_csv(elo_path, parse_dates=["date"])

    # Merge ELO onto matches
    df = matches.merge(
        elo_hist[["date", "home_team", "away_team",
                  "home_elo_before", "away_elo_before"]],
        on=["date", "home_team", "away_team"],
        how="left",
    )
    df["elo_diff"] = df["home_elo_before"] - df["away_elo_before"]

    # Squad strength (static — uses latest FIFA data)
    if os.path.exists(squad_path):
        sq = pd.read_csv(squad_path).set_index("team")["squad_strength"]
        df["home_squad_strength"] = df["home_team"].map(sq).fillna(70.0)
        df["away_squad_strength"] = df["away_team"].map(sq).fillna(70.0)
        df["squad_strength_diff"] = df["home_squad_strength"] - df["away_squad_strength"]
    else:
        df["squad_strength_diff"] = 0.0

    rows = []
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Features"):
        h, a, d = row.home_team, row.away_team, row.date

        h2h   = h2h_stats(matches, h, a, d)
        vf    = venue_form(matches, h, str(row.get("city", "")), d)
        h_frm = recent_form_points(matches, h, d)
        a_frm = recent_form_points(matches, a, d)
        h_rest = days_since_last_match(matches, h, d)
        a_rest = days_since_last_match(matches, a, d)
        h_gs, h_gc = goals_avg(matches, h, d)
        a_gs, a_gc = goals_avg(matches, a, d)

        rows.append({
            "date":                row.date,
            "home_team":           h,
            "away_team":           a,
            "result":              row.result,
            "tournament_weight":   row.tournament_weight,
            "elo_diff":            row.get("elo_diff", 0),
            "home_elo":            row.get("home_elo_before", 1500),
            "away_elo":            row.get("away_elo_before", 1500),
            "squad_strength_diff": row.get("squad_strength_diff", 0),
            "home_recent_form":    h_frm,
            "away_recent_form":    a_frm,
            "h2h_home_wins":       h2h["h2h_home_wins"],
            "h2h_draws":           h2h["h2h_draws"],
            "h2h_away_wins":       h2h["h2h_away_wins"],
            "venue_win_rate":      vf,
            "home_goals_avg":      h_gs,
            "away_goals_avg":      a_gs,
            "home_goals_conceded": h_gc,
            "away_goals_conceded": a_gc,
            "days_rest_home":      h_rest,
            "days_rest_away":      a_rest,
            "is_neutral":          int(row.neutral),
        })

    features = pd.DataFrame(rows)
    out = os.path.join(PROCESSED, "features_final.csv")
    features.to_csv(out, index=False)
    print(f"  Saved feature table ({len(features):,} rows × {features.shape[1]} cols) → {out}")
    return features
"""

# ── src/models/train.py ───────────────────────────────────────────────────────
FILES["src/models/train.py"] = """
\"\"\"
Train GradientBoosting and XGBoost classifiers on features_final.csv.
Saves models/gbm_model.pkl and models/xgb_model.pkl.
\"\"\"

import os
import joblib
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

try:
    from xgboost import XGBClassifier
    HAS_XGB = True
except ImportError:
    HAS_XGB = False

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")
MODELS    = os.path.join(os.path.dirname(__file__), "..", "..", "models")

FEATURE_COLS = [
    "elo_diff", "squad_strength_diff",
    "home_recent_form", "away_recent_form",
    "h2h_home_wins", "h2h_draws", "h2h_away_wins",
    "venue_win_rate",
    "home_goals_avg", "away_goals_avg",
    "home_goals_conceded", "away_goals_conceded",
    "days_rest_home", "days_rest_away",
    "is_neutral", "tournament_weight",
]


def train_model() -> None:
    os.makedirs(MODELS, exist_ok=True)
    path = os.path.join(PROCESSED, "features_final.csv")
    if not os.path.exists(path):
        raise FileNotFoundError("Run build_features() first.")

    df = pd.read_csv(path).dropna(subset=FEATURE_COLS + ["result"])
    X = df[FEATURE_COLS]
    y = df["result"].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_test_s  = scaler.transform(X_test)

    # GBM
    gbm = GradientBoostingClassifier(
        n_estimators=300, learning_rate=0.05,
        max_depth=4, subsample=0.8, random_state=42,
    )
    gbm.fit(X_train_s, y_train)
    gbm_acc = accuracy_score(y_test, gbm.predict(X_test_s))
    print(f"  GBM accuracy : {gbm_acc:.4f}")
    print(classification_report(y_test, gbm.predict(X_test_s),
                                 target_names=["Home Win", "Draw", "Away Win"]))

    joblib.dump(gbm,    os.path.join(MODELS, "gbm_model.pkl"))
    joblib.dump(scaler, os.path.join(MODELS, "scaler.pkl"))
    print(f"  Saved gbm_model.pkl and scaler.pkl → {MODELS}/")

    # XGBoost (optional)
    if HAS_XGB:
        xgb = XGBClassifier(
            n_estimators=300, learning_rate=0.05,
            max_depth=4, subsample=0.8,
            use_label_encoder=False, eval_metric="mlogloss",
            random_state=42, n_jobs=-1,
        )
        xgb.fit(X_train_s, y_train)
        xgb_acc = accuracy_score(y_test, xgb.predict(X_test_s))
        print(f"  XGB accuracy : {xgb_acc:.4f}")
        joblib.dump(xgb, os.path.join(MODELS, "xgb_model.pkl"))
        print(f"  Saved xgb_model.pkl → {MODELS}/")
    else:
        print("  (xgboost not installed — skipping XGB training)")
"""

# ── src/models/evaluate.py ────────────────────────────────────────────────────
FILES["src/models/evaluate.py"] = """
\"\"\"
Load saved model and print accuracy, confusion matrix, and SHAP summary.
\"\"\"

import os
import joblib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

try:
    import shap
    HAS_SHAP = True
except ImportError:
    HAS_SHAP = False

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")
MODELS    = os.path.join(os.path.dirname(__file__), "..", "..", "models")

FEATURE_COLS = [
    "elo_diff", "squad_strength_diff",
    "home_recent_form", "away_recent_form",
    "h2h_home_wins", "h2h_draws", "h2h_away_wins",
    "venue_win_rate",
    "home_goals_avg", "away_goals_avg",
    "home_goals_conceded", "away_goals_conceded",
    "days_rest_home", "days_rest_away",
    "is_neutral", "tournament_weight",
]


def evaluate(model_name: str = "gbm_model.pkl") -> None:
    model  = joblib.load(os.path.join(MODELS, model_name))
    scaler = joblib.load(os.path.join(MODELS, "scaler.pkl"))

    df = pd.read_csv(os.path.join(PROCESSED, "features_final.csv")).dropna(subset=FEATURE_COLS)
    X = scaler.transform(df[FEATURE_COLS])
    y = df["result"].astype(int)

    preds = model.predict(X)
    print(f"Overall accuracy: {accuracy_score(y, preds):.4f}")

    cm = confusion_matrix(y, preds)
    disp = ConfusionMatrixDisplay(cm, display_labels=["Home Win", "Draw", "Away Win"])
    disp.plot(cmap="Blues")
    plt.title(f"Confusion Matrix — {model_name}")
    plt.tight_layout()
    plt.show()

    if HAS_SHAP:
        explainer = shap.Explainer(model, X)
        shap_vals = explainer(X[:500])
        shap.summary_plot(shap_vals, features=df[FEATURE_COLS].iloc[:500],
                          feature_names=FEATURE_COLS, plot_type="bar")


if __name__ == "__main__":
    evaluate()
"""

# ── src/models/predict.py ─────────────────────────────────────────────────────
FILES["src/models/predict.py"] = """
\"\"\"
Load trained model and return win/draw/loss probabilities for any two teams.
\"\"\"

import os
import joblib
import numpy as np
import pandas as pd

MODELS    = os.path.join(os.path.dirname(__file__), "..", "..", "models")
PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")

FEATURE_COLS = [
    "elo_diff", "squad_strength_diff",
    "home_recent_form", "away_recent_form",
    "h2h_home_wins", "h2h_draws", "h2h_away_wins",
    "venue_win_rate",
    "home_goals_avg", "away_goals_avg",
    "home_goals_conceded", "away_goals_conceded",
    "days_rest_home", "days_rest_away",
    "is_neutral", "tournament_weight",
]

_model  = None
_scaler = None


def _load():
    global _model, _scaler
    if _model is None:
        for name in ("xgb_model.pkl", "gbm_model.pkl"):
            p = os.path.join(MODELS, name)
            if os.path.exists(p):
                _model = joblib.load(p)
                break
        _scaler = joblib.load(os.path.join(MODELS, "scaler.pkl"))


def _get_elo(team: str) -> float:
    snap = os.path.join(PROCESSED, "elo_snapshot.csv")
    if not os.path.exists(snap):
        return 1500.0
    df = pd.read_csv(snap)
    row = df[df["team"] == team]
    return float(row.iloc[0]["elo"]) if not row.empty else 1500.0


def _get_squad_strength(team: str) -> float:
    path = os.path.join(PROCESSED, "squad_strength.csv")
    if not os.path.exists(path):
        return 70.0
    df = pd.read_csv(path)
    row = df[df["team"] == team]
    return float(row.iloc[0]["squad_strength"]) if not row.empty else 70.0


def predict_match(
    home: str,
    away: str,
    is_neutral: bool = False,
    tournament_weight: int = 3,
) -> dict:
    \"\"\"
    Return {"home_win": p, "draw": p, "away_win": p} for a given fixture.
    \"\"\"
    _load()

    h_elo = _get_elo(home)
    a_elo = _get_elo(away)
    h_sq  = _get_squad_strength(home)
    a_sq  = _get_squad_strength(away)

    features = {
        "elo_diff":            h_elo - a_elo,
        "squad_strength_diff": h_sq  - a_sq,
        "home_recent_form":    1.5,   # neutral default
        "away_recent_form":    1.5,
        "h2h_home_wins":       0,
        "h2h_draws":           0,
        "h2h_away_wins":       0,
        "venue_win_rate":      0.5,
        "home_goals_avg":      1.2,
        "away_goals_avg":      1.2,
        "home_goals_conceded": 1.0,
        "away_goals_conceded": 1.0,
        "days_rest_home":      7,
        "days_rest_away":      7,
        "is_neutral":          int(is_neutral),
        "tournament_weight":   tournament_weight,
    }

    X = np.array([[features[c] for c in FEATURE_COLS]])
    X_s = _scaler.transform(X)
    probs = _model.predict_proba(X_s)[0]

    # Map class indices to labels (sorted: 0=home, 1=draw, 2=away)
    classes = _model.classes_
    label_map = {0: "home_win", 1: "draw", 2: "away_win"}
    result = {label_map[c]: round(float(p), 4) for c, p in zip(classes, probs)}
    return result
"""

# ── app/app.py ────────────────────────────────────────────────────────────────
FILES["app/app.py"] = """
\"\"\"
Streamlit entry point.  Run with:
    streamlit run app/app.py
\"\"\"

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import streamlit as st

st.set_page_config(
    page_title="⚽ World Cup 2026 Predictor",
    page_icon="⚽",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("⚽ World Cup 2026 Predictor")
st.markdown(
    \"\"\"
    Welcome! Use the sidebar to navigate between pages:

    | Page | Description |
    |------|-------------|
    | 🔮 Match Predictor | Pick two teams and get win/draw/loss probabilities |
    | 📈 ELO Tracker | View any team's ELO rating over time |
    | 🧑‍🤝‍🧑 Squad Analysis | Compare squad strength between teams |
    | 🏆 Tournament Simulator | Simulate the full 2026 bracket |
    \"\"\"
)
"""

# ── app/pages/01_match_predictor.py ───────────────────────────────────────────
FILES["app/pages/01_match_predictor.py"] = """
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import streamlit as st
import pandas as pd
from src.models.predict import predict_match

st.title("🔮 Match Predictor")

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")

@st.cache_data
def team_list():
    snap = os.path.join(PROCESSED, "elo_snapshot.csv")
    if os.path.exists(snap):
        return sorted(pd.read_csv(snap)["team"].tolist())
    return ["Brazil", "France", "Argentina", "England", "Spain",
            "Germany", "Portugal", "Netherlands"]

teams = team_list()

col1, col2 = st.columns(2)
with col1:
    home = st.selectbox("🏠 Home Team", teams, index=0)
with col2:
    away = st.selectbox("✈️ Away Team", teams, index=1)

neutral = st.checkbox("Neutral venue?")

if st.button("Predict Match", type="primary"):
    try:
        result = predict_match(home, away, is_neutral=neutral)
        st.subheader("Predicted Probabilities")
        c1, c2, c3 = st.columns(3)
        c1.metric(f"🏠 {home} Win", f"{result['home_win']*100:.1f}%")
        c2.metric("🤝 Draw",        f"{result['draw']*100:.1f}%")
        c3.metric(f"✈️ {away} Win", f"{result['away_win']*100:.1f}%")

        import plotly.graph_objects as go
        fig = go.Figure(go.Bar(
            x=[f"{home} Win", "Draw", f"{away} Win"],
            y=[result["home_win"], result["draw"], result["away_win"]],
            marker_color=["#1f77b4", "#aec7e8", "#ff7f0e"],
        ))
        fig.update_layout(yaxis_tickformat=".0%", title="Win Probability")
        st.plotly_chart(fig, use_container_width=True)
    except Exception as e:
        st.error(f"Could not predict: {e}. Make sure you've run pipeline.py first.")
"""

# ── app/pages/02_elo_tracker.py ───────────────────────────────────────────────
FILES["app/pages/02_elo_tracker.py"] = """
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("📈 ELO Tracker")

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")
elo_path = os.path.join(PROCESSED, "elo_history.csv")

if not os.path.exists(elo_path):
    st.warning("ELO history not found. Run pipeline.py first.")
    st.stop()

@st.cache_data
def load_elo():
    df = pd.read_csv(elo_path, parse_dates=["date"])
    home = df[["date", "home_team", "home_elo_after"]].rename(
        columns={"home_team": "team", "home_elo_after": "elo"})
    away = df[["date", "away_team", "away_elo_after"]].rename(
        columns={"away_team": "team", "away_elo_after": "elo"})
    return pd.concat([home, away]).sort_values("date")

history = load_elo()
all_teams = sorted(history["team"].unique())
selected  = st.multiselect("Select teams", all_teams, default=all_teams[:5])

if selected:
    sub = history[history["team"].isin(selected)]
    fig = px.line(sub, x="date", y="elo", color="team", title="ELO Rating Over Time")
    st.plotly_chart(fig, use_container_width=True)
"""

# ── app/pages/03_squad_analysis.py ───────────────────────────────────────────
FILES["app/pages/03_squad_analysis.py"] = """
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("🧑‍🤝‍🧑 Squad Strength Analysis")

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")
sq_path  = os.path.join(PROCESSED, "squad_strength.csv")
pss_path = os.path.join(PROCESSED, "player_pss.csv")

if not os.path.exists(sq_path):
    st.warning("Squad strength data not found. Run pipeline.py first.")
    st.stop()

sq  = pd.read_csv(sq_path)
top = sq.head(30)

fig = px.bar(top, x="squad_strength", y="team", orientation="h",
             title="Top 30 National Teams — Squad Strength Score",
             color="squad_strength", color_continuous_scale="Blues")
fig.update_layout(yaxis=dict(autorange="reversed"))
st.plotly_chart(fig, use_container_width=True)

if os.path.exists(pss_path):
    pss = pd.read_csv(pss_path)
    team = st.selectbox("Drill into a team", sorted(pss["nationality"].dropna().unique()))
    sub  = pss[pss["nationality"] == team].sort_values("PSS", ascending=False).head(23)
    st.dataframe(sub[["short_name", "club_name", "PSS"]], use_container_width=True)
"""

# ── app/pages/04_tournament_sim.py ───────────────────────────────────────────
FILES["app/pages/04_tournament_sim.py"] = """
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import streamlit as st
import pandas as pd
import numpy as np
from collections import defaultdict
from src.models.predict import predict_match

st.title("🏆 2026 World Cup Simulator")

# 48-team field (representative subset for demo)
DEFAULT_TEAMS = [
    "Brazil", "France", "Argentina", "England", "Spain", "Germany",
    "Portugal", "Netherlands", "Belgium", "Italy", "Croatia", "Uruguay",
    "Mexico", "United States", "Morocco", "Senegal", "Japan", "South Korea",
    "Australia", "Ecuador", "Colombia", "Chile", "Poland", "Switzerland",
    "Denmark", "Austria", "Turkey", "Serbia", "Ukraine", "Iran",
    "Saudi Arabia", "Qatar",
]

n_sims = st.slider("Number of simulations", 100, 5000, 1000, step=100)

if st.button("Run Monte Carlo Simulation ▶", type="primary"):
    wins = defaultdict(int)
    teams = DEFAULT_TEAMS

    progress = st.progress(0)
    for i in range(n_sims):
        pool = teams.copy()
        np.random.shuffle(pool)
        # Simple single-elimination bracket
        while len(pool) > 1:
            next_round = []
            for j in range(0, len(pool) - 1, 2):
                h, a = pool[j], pool[j+1]
                try:
                    p = predict_match(h, a, is_neutral=True)
                    r = np.random.choice(["home_win", "draw", "away_win"],
                                         p=[p["home_win"], p["draw"], p["away_win"]])
                    next_round.append(h if r in ("home_win", "draw") else a)
                except Exception:
                    next_round.append(h)
            if len(pool) % 2 == 1:
                next_round.append(pool[-1])
            pool = next_round
        wins[pool[0]] += 1
        progress.progress((i + 1) / n_sims)

    progress.empty()
    results = (
        pd.DataFrame({"team": list(wins.keys()), "wins": list(wins.values())})
        .sort_values("wins", ascending=False)
        .assign(probability=lambda d: d.wins / n_sims)
    )

    import plotly.express as px
    fig = px.bar(results.head(16), x="probability", y="team", orientation="h",
                 title=f"Tournament Win Probability ({n_sims:,} simulations)",
                 color="probability", color_continuous_scale="Greens")
    fig.update_layout(yaxis=dict(autorange="reversed"), xaxis_tickformat=".0%")
    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(results, use_container_width=True)
"""

# ── app/components/team_card.py ───────────────────────────────────────────────
FILES["app/components/team_card.py"] = """
import streamlit as st
import pandas as pd
import os

PROCESSED = os.path.join(os.path.dirname(__file__), "..", "..", "data", "processed")


def team_card(team_name: str) -> None:
    \"\"\"Display a simple info card for a national team.\"\"\"
    st.subheader(team_name)

    snap = os.path.join(PROCESSED, "elo_snapshot.csv")
    if os.path.exists(snap):
        df = pd.read_csv(snap)
        row = df[df["team"] == team_name]
        if not row.empty:
            st.metric("ELO Rating", f"{row.iloc[0]['elo']:.0f}")

    sq_path = os.path.join(PROCESSED, "squad_strength.csv")
    if os.path.exists(sq_path):
        df2 = pd.read_csv(sq_path)
        row2 = df2[df2["team"] == team_name]
        if not row2.empty:
            st.metric("Squad Strength", f"{row2.iloc[0]['squad_strength']:.1f}")
"""

# ── app/components/prob_chart.py ─────────────────────────────────────────────
FILES["app/components/prob_chart.py"] = """
import plotly.graph_objects as go


def prob_chart(home: str, away: str, probs: dict) -> go.Figure:
    \"\"\"Return a horizontal bar chart of win/draw/loss probabilities.\"\"\"
    labels = [f"{home} Win", "Draw", f"{away} Win"]
    values = [probs.get("home_win", 0), probs.get("draw", 0), probs.get("away_win", 0)]
    colors = ["#2196F3", "#9E9E9E", "#FF5722"]

    fig = go.Figure(go.Bar(
        x=values, y=labels, orientation="h",
        marker_color=colors,
        text=[f"{v*100:.1f}%" for v in values],
        textposition="auto",
    ))
    fig.update_layout(
        title="Match Outcome Probabilities",
        xaxis=dict(tickformat=".0%", range=[0, 1]),
        height=250,
        margin=dict(l=10, r=10, t=40, b=10),
    )
    return fig
"""

# ── tests/ ────────────────────────────────────────────────────────────────────
FILES["tests/__init__.py"] = ""

FILES["tests/test_elo.py"] = """
\"\"\"Unit tests for ELO calculation logic.\"\"\"
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from collections import defaultdict
from src.elo.base_elo import expected_score, update_match_elo
from src.utils.constants import DEFAULT_ELO


def test_expected_score_equal_teams():
    assert abs(expected_score(1500, 1500) - 0.5) < 1e-9


def test_expected_score_stronger_team():
    assert expected_score(2000, 1500) > 0.5


def test_elo_increases_on_win():
    elo = defaultdict(lambda: DEFAULT_ELO)
    elo["A"] = 1500
    elo["B"] = 1500
    before = elo["A"]
    update_match_elo(elo, "A", "B", 1, 0, True, "Friendly")
    assert elo["A"] > before


def test_elo_decreases_on_loss():
    elo = defaultdict(lambda: DEFAULT_ELO)
    before = elo["A"]
    update_match_elo(elo, "A", "B", 0, 1, True, "Friendly")
    assert elo["A"] < before


def test_draw_on_equal_teams_no_change():
    elo = defaultdict(lambda: DEFAULT_ELO)
    elo["A"] = elo["B"] = 1500
    update_match_elo(elo, "A", "B", 1, 1, True, "Friendly")
    # Small change expected since expected score ~ 0.5 and actual = 0.5
    assert abs(elo["A"] - 1500) < 1.0


if __name__ == "__main__":
    test_expected_score_equal_teams()
    test_expected_score_stronger_team()
    test_elo_increases_on_win()
    test_elo_decreases_on_loss()
    test_draw_on_equal_teams_no_change()
    print("All ELO tests passed ✅")
"""

FILES["tests/test_features.py"] = """
\"\"\"Unit tests for feature helper functions.\"\"\"
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pandas as pd
from src.features.match_features import h2h_stats, recent_form_points, goals_avg


def _sample_df():
    return pd.DataFrame({
        "date":       pd.to_datetime(["2020-01-01", "2020-06-01", "2021-01-01"]),
        "home_team":  ["Brazil", "Brazil", "France"],
        "away_team":  ["France", "Argentina", "Brazil"],
        "home_score": [2, 1, 0],
        "away_score": [1, 0, 2],
        "neutral":    [False, False, True],
        "result":     [0, 0, 2],
        "city":       ["Rio", "Sao Paulo", "Paris"],
        "tournament_weight": [3, 2, 3],
    })


def test_h2h_stats_returns_dict():
    df = _sample_df()
    result = h2h_stats(df, "Brazil", "France", "2022-01-01")
    assert isinstance(result, dict)
    assert "h2h_home_wins" in result


def test_recent_form_no_matches():
    df = _sample_df()
    # Germany has no matches — should return neutral default
    form = recent_form_points(df, "Germany", "2022-01-01")
    assert form == 1.0


def test_goals_avg_returns_tuple():
    df = _sample_df()
    scored, conceded = goals_avg(df, "Brazil", "2022-01-01")
    assert isinstance(scored, float)
    assert isinstance(conceded, float)


if __name__ == "__main__":
    test_h2h_stats_returns_dict()
    test_recent_form_no_matches()
    test_goals_avg_returns_tuple()
    print("All feature tests passed ✅")
"""

FILES["tests/test_predict.py"] = """
\"\"\"
Smoke test for prediction pipeline.
Skipped automatically if models have not been trained yet.
\"\"\"
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import pytest

MODELS = os.path.join(os.path.dirname(__file__), "..", "models")


def models_exist():
    return os.path.exists(os.path.join(MODELS, "scaler.pkl")) and any(
        os.path.exists(os.path.join(MODELS, f))
        for f in ("gbm_model.pkl", "xgb_model.pkl")
    )


@pytest.mark.skipif(not models_exist(), reason="Models not trained yet")
def test_predict_returns_three_probs():
    from src.models.predict import predict_match
    result = predict_match("Brazil", "France", is_neutral=True)
    assert "home_win" in result and "draw" in result and "away_win" in result
    total = result["home_win"] + result["draw"] + result["away_win"]
    assert abs(total - 1.0) < 0.01


if __name__ == "__main__":
    if models_exist():
        test_predict_returns_three_probs()
        print("Prediction test passed ✅")
    else:
        print("Skipped — run pipeline.py first to train models.")
"""

# ── External JSON stubs ───────────────────────────────────────────────────────
FILES["data/external/star_players.json"] = """{
  "Brazil":      ["Vinicius Jr", "Rodrygo"],
  "France":      ["Kylian Mbappe", "Antoine Griezmann"],
  "Argentina":   ["Lionel Messi", "Julian Alvarez"],
  "England":     ["Jude Bellingham", "Harry Kane"],
  "Spain":       ["Pedri", "Lamine Yamal"],
  "Germany":     ["Florian Wirtz", "Jamal Musiala"],
  "Portugal":    ["Cristiano Ronaldo", "Bruno Fernandes"],
  "Netherlands": ["Virgil van Dijk", "Cody Gakpo"],
  "Belgium":     ["Kevin De Bruyne", "Romelu Lukaku"],
  "Italy":       ["Federico Chiesa", "Nicolo Barella"]
}
"""

FILES["data/external/venue_metadata.json"] = """{
  "La Paz":        {"altitude_m": 3640, "country": "Bolivia",  "surface": "grass"},
  "Quito":         {"altitude_m": 2850, "country": "Ecuador",  "surface": "grass"},
  "Mexico City":   {"altitude_m": 2240, "country": "Mexico",   "surface": "grass"},
  "Bogota":        {"altitude_m": 2600, "country": "Colombia", "surface": "grass"},
  "New York":      {"altitude_m":    3, "country": "USA",      "surface": "grass"},
  "Los Angeles":   {"altitude_m":   71, "country": "USA",      "surface": "grass"},
  "Dallas":        {"altitude_m":  183, "country": "USA",      "surface": "artificial"},
  "Toronto":       {"altitude_m":   76, "country": "Canada",   "surface": "grass"}
}
"""

FILES["data/external/injury_list.json"] = """{
  "_comment": "Update this manually before generating predictions.",
  "Brazil":    [],
  "France":    [],
  "Argentina": [],
  "England":   [],
  "Spain":     [],
  "Germany":   []
}
"""

# ── Placeholder __init__ files for app dirs ───────────────────────────────────
FILES["app/__init__.py"] = ""
FILES["app/pages/__init__.py"] = ""
FILES["app/components/__init__.py"] = ""

# ── Empty placeholder dirs (no files needed, just make them) ─────────────────
EMPTY_DIRS = [
    "data/raw",
    "data/processed",
    "models",
    "notebooks",
]

# ══════════════════════════════════════════════════════════════════════════════
#  CREATE EVERYTHING
# ══════════════════════════════════════════════════════════════════════════════

def main():
    print(f"\nCreating project at: {os.path.abspath(BASE)}\n")

    for d in EMPTY_DIRS:
        mkdir(os.path.join(BASE, d))
        print(f"  created  {os.path.join(BASE, d)}/")

    for rel_path, content in FILES.items():
        write(os.path.join(BASE, rel_path), content)

    print(f"\n✅  Project created successfully at  ./{BASE}/")
    print("\nNext steps:")
    print("  1.  pip install -r world_cup_predictor/requirements.txt")
    print("  2.  Drop your Kaggle CSVs into  world_cup_predictor/data/raw/")
    print("  3.  cd world_cup_predictor && python pipeline.py")
    print("  4.  streamlit run app/app.py")


if __name__ == "__main__":
    main()
